Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,7 +5,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
       - uses: actions/setup-python@v4
         with:
           python-version: '3.10'
@@ -14,12 +14,15 @@ jobs:
           pip install flet requests pandas ta websocket-client
       - name: Build APK
         run: |
-          # الموافقة التلقائية على تراخيص أندرويد
           yes "y" | flutter doctor --android-licenses || true
-          # بناء التطبيق مع تحديد ملف sun.py كملف أساسي
           flet build apk --project "MahmoudTerminal" --module-name sun.py --yes
+      
+      # خطوة إضافية للتأكد من وجود الملف (Debug)
+      - name: List built files
+        run: ls -R build/apk/ || echo "Folder not found"
+
       - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
           name: app-apk
-          path: build/apk/app-release.apk
+          path: build/apk/*.apk
